[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
axum = { version = "0.7.7", features = ["macros"] }
listenfd = "1.0.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio =  { version = "1.40.0",  features = ["rt", "rt-multi-thread", "macros"] }
